/* =========================================================================
 * NurseTube（ナースチューブ）— 看護師のための勉強用YouTube
 * 番組カタログのデータ定義
 *
 * ▼ 自分の動画を追加・差し替えするには
 *   下の PROGRAMS 配列に項目を足すだけです。
 *   videoId にYouTubeの動画ID（例: https://www.youtube.com/watch?v=XXXXXXXXXXX の XXXXXXXXXXX）
 *   を入れると、視聴ページで埋め込み再生されます。
 *   videoId を空 "" にしておくと、「YouTubeで検索して視聴」ボタンに切り替わります。
 * ========================================================================= */

// 看護師国家試験の目標日（ヘッダーのカウントダウン用。自由に変更してください）
const EXAM_DATE = "2027-02-14";

// カテゴリ定義（key はデータと一致させる。color はサムネイルの配色に使われます）
const CATEGORIES = [
  { key: "all",        label: "ホーム",       icon: "🏠", color: "#ef4444" },
  { key: "基礎看護学",   label: "基礎看護学",   icon: "🩺", color: "#2563eb" },
  { key: "解剖生理学",   label: "解剖生理学",   icon: "🫀", color: "#db2777" },
  { key: "薬理学",      label: "薬理学",       icon: "💊", color: "#7c3aed" },
  { key: "疾患・病態",   label: "疾患・病態",   icon: "🧬", color: "#16a34a" },
  { key: "看護技術",     label: "看護技術",     icon: "💉", color: "#0891b2" },
  { key: "母性・小児",   label: "母性・小児",   icon: "🍼", color: "#f59e0b" },
  { key: "精神看護",     label: "精神看護",     icon: "🧠", color: "#4f46e5" },
  { key: "国家試験対策", label: "国家試験対策", icon: "📝", color: "#dc2626" },
];

// 番組（学習動画）カタログ
const PROGRAMS = [
  // --- 解剖生理学 ---
  {
    id: "anat01",
    title: "心臓の解剖と血液の流れを10分で完全マスター",
    category: "解剖生理学",
    channel: "ナース解剖チャンネル",
    durationSec: 612,
    views: 128400,
    published: "2026-04-12",
    videoId: "",
    description: "右心房・右心室・左心房・左心室の位置関係と、体循環・肺循環の血液の流れを図解で整理します。弁の名前と役割、心電図との対応まで、国家試験で問われるポイントを一気にまとめました。",
    tags: ["循環器", "解剖", "必修"],
  },
  {
    id: "anat02",
    title: "腎臓のはたらき｜ネフロンと尿ができる仕組み",
    category: "解剖生理学",
    channel: "ナース解剖チャンネル",
    durationSec: 845,
    views: 96200,
    published: "2026-03-02",
    videoId: "",
    description: "糸球体でのろ過、尿細管での再吸収・分泌の流れをステップで解説。RAA系やADHによる調節、電解質バランスとのつながりも押さえます。",
    tags: ["腎・泌尿器", "解剖", "国試"],
  },
  {
    id: "anat03",
    title: "呼吸のメカニズムとガス交換のしくみ",
    category: "解剖生理学",
    channel: "ナース解剖チャンネル",
    durationSec: 540,
    views: 71300,
    published: "2026-02-18",
    videoId: "",
    description: "外呼吸と内呼吸の違い、酸素解離曲線、換気と血流の関係を丁寧に解説。SpO2やPaO2の見方にもつなげます。",
    tags: ["呼吸器", "解剖"],
  },
  {
    id: "anat04",
    title: "自律神経まとめ｜交感神経と副交感神経の作用一覧",
    category: "解剖生理学",
    channel: "ナース解剖チャンネル",
    durationSec: 498,
    views: 113900,
    published: "2026-05-09",
    videoId: "",
    description: "瞳孔・心拍・消化・血圧など、臓器ごとの交感／副交感の作用を表で暗記。薬理(自律神経作用薬)の理解にも直結します。",
    tags: ["神経", "暗記", "薬理連携"],
  },
  {
    id: "anat05",
    title: "ホルモンと内分泌系の全体像をスッキリ整理",
    category: "解剖生理学",
    channel: "ナース解剖チャンネル",
    durationSec: 760,
    views: 58700,
    published: "2026-01-21",
    videoId: "",
    description: "視床下部—下垂体—標的器官の流れと、主要ホルモンの作用・分泌異常(亢進/低下)で起こる疾患をまとめて学習します。",
    tags: ["内分泌", "解剖"],
  },

  // --- 基礎看護学 ---
  {
    id: "base01",
    title: "バイタルサイン測定の基本と正常値【保存版】",
    category: "基礎看護学",
    channel: "やさしい基礎看護",
    durationSec: 935,
    views: 204500,
    published: "2026-04-28",
    videoId: "",
    description: "体温・脈拍・呼吸・血圧・SpO2の正常値と測定手順、異常時の考え方を実演を交えて解説。臨地実習の前に必ず見ておきたい1本です。",
    tags: ["バイタル", "必修", "実習前"],
  },
  {
    id: "base02",
    title: "感染予防の基本｜スタンダードプリコーションと手指衛生5つの瞬間",
    category: "基礎看護学",
    channel: "やさしい基礎看護",
    durationSec: 612,
    views: 88100,
    published: "2026-03-15",
    videoId: "",
    description: "標準予防策の考え方、手指衛生のタイミング、個人防護具(PPE)の着脱順序を整理。感染経路別予防策との違いも解説します。",
    tags: ["感染", "実習前", "必修"],
  },
  {
    id: "base03",
    title: "看護過程の進め方｜アセスメントから看護診断まで",
    category: "基礎看護学",
    channel: "やさしい基礎看護",
    durationSec: 1080,
    views: 67400,
    published: "2026-02-06",
    videoId: "",
    description: "情報収集→アセスメント→看護診断→計画→実施→評価の流れを、具体例を使って分かりやすく解説。実習記録が苦手な人向けです。",
    tags: ["看護過程", "実習", "記録"],
  },
  {
    id: "base04",
    title: "SOAPの書き方入門｜記録が苦手でも書けるコツ",
    category: "基礎看護学",
    channel: "やさしい基礎看護",
    durationSec: 524,
    views: 79900,
    published: "2026-05-20",
    videoId: "",
    description: "S(主観)・O(客観)・A(アセスメント)・P(計画)の分け方と、よくある間違いを例文で解説。実習記録のスピードが上がります。",
    tags: ["記録", "実習"],
  },

  // --- 看護技術 ---
  {
    id: "skill01",
    title: "静脈血採血の手順とコツ｜駆血から抜針まで",
    category: "看護技術",
    channel: "看護技術ラボ",
    durationSec: 702,
    views: 152300,
    published: "2026-04-03",
    videoId: "",
    description: "必要物品、血管の選び方、駆血帯の位置、刺入角度、スピッツの順番、抜針と止血までを実演で解説。神経損傷を避けるポイントも。",
    tags: ["採血", "手技", "実習"],
  },
  {
    id: "skill02",
    title: "膀胱留置カテーテルの挿入｜無菌操作のポイント",
    category: "看護技術",
    channel: "看護技術ラボ",
    durationSec: 688,
    views: 64800,
    published: "2026-03-22",
    videoId: "",
    description: "男性・女性の解剖の違い、消毒の範囲、固定水の量、感染予防の注意点をまとめて解説します。",
    tags: ["導尿", "手技", "感染予防"],
  },
  {
    id: "skill03",
    title: "褥瘡予防とポジショニング｜体位変換の基本",
    category: "看護技術",
    channel: "看護技術ラボ",
    durationSec: 595,
    views: 51200,
    published: "2026-02-11",
    videoId: "",
    description: "DESIGN-R®の見方、好発部位、30度側臥位、ずれ・圧の減らし方を解説。栄養管理との関係にも触れます。",
    tags: ["褥瘡", "スキンケア"],
  },
  {
    id: "skill04",
    title: "経鼻胃管(NGチューブ)挿入と管理のポイント",
    category: "看護技術",
    channel: "看護技術ラボ",
    durationSec: 640,
    views: 43900,
    published: "2026-01-30",
    videoId: "",
    description: "挿入の長さの測り方、位置確認の方法、固定、栄養剤投与時の注意点を解説。誤挿入を防ぐ確認手順を重点的に。",
    tags: ["経管栄養", "手技"],
  },
  {
    id: "skill05",
    title: "口腔・鼻腔・気管吸引の手順と注意点",
    category: "看護技術",
    channel: "看護技術ラボ",
    durationSec: 558,
    views: 60100,
    published: "2026-05-02",
    videoId: "",
    description: "吸引圧、1回の吸引時間、低酸素予防、清潔操作のポイントを整理。SpO2モニタリングとあわせて解説します。",
    tags: ["吸引", "呼吸", "手技"],
  },

  // --- 薬理学 ---
  {
    id: "pharm01",
    title: "降圧薬の種類と作用機序をまとめて理解",
    category: "薬理学",
    channel: "やさしい薬理学",
    durationSec: 815,
    views: 92700,
    published: "2026-04-18",
    videoId: "",
    description: "Ca拮抗薬・ARB・ACE阻害薬・利尿薬・β遮断薬の作用点と代表的な副作用を整理。語呂と図でまとめます。",
    tags: ["循環器", "薬理", "国試"],
  },
  {
    id: "pharm02",
    title: "インスリン製剤の種類と作用時間【超速効〜持効型】",
    category: "薬理学",
    channel: "やさしい薬理学",
    durationSec: 612,
    views: 70500,
    published: "2026-03-08",
    videoId: "",
    description: "超速効型・速効型・中間型・持効型の作用発現と持続時間、低血糖症状とシックデイの対応を解説します。",
    tags: ["糖尿病", "薬理", "必修"],
  },
  {
    id: "pharm03",
    title: "抗菌薬の分類と使い分けの基本",
    category: "薬理学",
    channel: "やさしい薬理学",
    durationSec: 705,
    views: 38600,
    published: "2026-02-24",
    videoId: "",
    description: "βラクタム系・マクロライド系・キノロン系などの分類と作用機序、耐性菌(MRSAなど)の基礎を整理します。",
    tags: ["感染", "薬理"],
  },
  {
    id: "pharm04",
    title: "利尿薬まとめ｜ループ・サイアザイド・K保持性",
    category: "薬理学",
    channel: "やさしい薬理学",
    durationSec: 486,
    views: 33100,
    published: "2026-01-14",
    videoId: "",
    description: "作用部位ごとの違いと電解質への影響(特に低K・高K)、観察ポイントを表で整理します。",
    tags: ["腎・泌尿器", "薬理"],
  },

  // --- 疾患・病態 ---
  {
    id: "dis01",
    title: "心不全の病態と看護｜左心不全と右心不全の違い",
    category: "疾患・病態",
    channel: "ナースのための病態塾",
    durationSec: 920,
    views: 84300,
    published: "2026-05-12",
    videoId: "",
    description: "前負荷・後負荷の考え方、左心不全(肺うっ血)と右心不全(体うっ血)の症状の違い、観察と看護のポイントを解説。",
    tags: ["循環器", "病態", "国試"],
  },
  {
    id: "dis02",
    title: "糖尿病の3大合併症をイメージで覚える",
    category: "疾患・病態",
    channel: "ナースのための病態塾",
    durationSec: 588,
    views: 119800,
    published: "2026-04-06",
    videoId: "",
    description: "神経障害・網膜症・腎症の機序と進行、フットケアや血糖コントロールの指導内容を整理します。",
    tags: ["糖尿病", "病態", "必修"],
  },
  {
    id: "dis03",
    title: "脳梗塞の分類と症状｜FASTで早期発見",
    category: "疾患・病態",
    channel: "ナースのための病態塾",
    durationSec: 640,
    views: 56700,
    published: "2026-03-19",
    videoId: "",
    description: "アテローム血栓性・心原性・ラクナの違い、t-PAの適応時間、片麻痺や失語などの症状と看護を解説します。",
    tags: ["脳神経", "病態"],
  },
  {
    id: "dis04",
    title: "COPDの病態と看護｜口すぼめ呼吸の意味",
    category: "疾患・病態",
    channel: "ナースのための病態塾",
    durationSec: 552,
    views: 41500,
    published: "2026-02-02",
    videoId: "",
    description: "閉塞性換気障害の機序、CO2ナルコーシスの注意点、呼吸リハと栄養管理のポイントを整理します。",
    tags: ["呼吸器", "病態"],
  },

  // --- 母性・小児 ---
  {
    id: "mat01",
    title: "正常分娩の経過と看護｜分娩第1期〜第4期",
    category: "母性・小児",
    channel: "母性・小児ナース教室",
    durationSec: 880,
    views: 47200,
    published: "2026-04-22",
    videoId: "",
    description: "分娩の3要素、各期の所要時間と観察項目、産婦への声かけと看護のポイントをまとめます。",
    tags: ["母性", "分娩"],
  },
  {
    id: "ped01",
    title: "新生児の生理とアセスメント｜アプガースコア",
    category: "母性・小児",
    channel: "母性・小児ナース教室",
    durationSec: 624,
    views: 39800,
    published: "2026-03-11",
    videoId: "",
    description: "アプガースコアの5項目、生理的体重減少や黄疸、原始反射など新生児の特徴をやさしく解説します。",
    tags: ["小児", "新生児"],
  },

  // --- 精神看護 ---
  {
    id: "psy01",
    title: "統合失調症の症状と看護｜陽性症状と陰性症状",
    category: "精神看護",
    channel: "メンタルナースch",
    durationSec: 705,
    views: 52600,
    published: "2026-05-16",
    videoId: "",
    description: "陽性症状(幻覚・妄想)と陰性症状(感情鈍麻・意欲低下)の違い、服薬支援と再発予防の関わりを解説します。",
    tags: ["精神", "看護"],
  },
  {
    id: "psy02",
    title: "うつ病の理解と関わり方｜してはいけない声かけ",
    category: "精神看護",
    channel: "メンタルナースch",
    durationSec: 567,
    views: 61900,
    published: "2026-04-09",
    videoId: "",
    description: "うつ病の症状と経過、希死念慮への対応、励ましが逆効果になる理由を具体例で解説します。",
    tags: ["精神", "看護"],
  },

  // --- 国家試験対策 ---
  {
    id: "exam01",
    title: "必修問題でよく出る正常値まとめ【一問一答】",
    category: "国家試験対策",
    channel: "こくし対策ゼミ",
    durationSec: 738,
    views: 233100,
    published: "2026-05-25",
    videoId: "",
    description: "バイタル・血液・電解質・尿などの基準値を一問一答形式で確認。必修8割の壁を超えるための頻出値を厳選しました。",
    tags: ["必修", "暗記", "国試"],
  },
  {
    id: "exam02",
    title: "点滴の滴下数 計算問題の解き方【公式と練習】",
    category: "国家試験対策",
    channel: "こくし対策ゼミ",
    durationSec: 612,
    views: 187500,
    published: "2026-04-15",
    videoId: "",
    description: "成人用(20滴=1mL)・小児用(60滴=1mL)の公式の使い分けと、よく出る計算パターンを練習問題で攻略します。",
    tags: ["計算", "必修", "国試"],
  },
  {
    id: "exam03",
    title: "心電図の読み方の基本｜まずはこの3つから",
    category: "国家試験対策",
    channel: "こくし対策ゼミ",
    durationSec: 690,
    views: 98400,
    published: "2026-03-28",
    videoId: "",
    description: "正常洞調律の見方、心房細動・心室細動・心室頻拍など危険な波形の特徴を、最低限おさえるべき形で解説します。",
    tags: ["循環器", "心電図", "国試"],
  },
];
