/* =========================================================================
 * NurseTube（ナースチューブ）— 看護師のための勉強用YouTube
 * 〜 ずんだもんが看護をやさしく解説してくれるチャンネルなのだ 〜
 * 番組カタログのデータ定義
 *
 * ▼ 自分の動画を追加・差し替えするには
 *   下の PROGRAMS 配列に項目を足すだけです。
 *   videoId にYouTubeの動画ID（例: https://www.youtube.com/watch?v=XXXXXXXXXXX の XXXXXXXXXXX）
 *   を入れると、視聴ページで埋め込み再生されます。
 *   videoId を空 "" にしておくと、「YouTubeで検索して視聴」ボタンに切り替わります。
 * ========================================================================= */

// 看護師国家試験の目標日（ヘッダーのカウントダウン用。自由に変更してください）
const EXAM_DATE = "2027-02-14";

// 解説してくれるキャラクター（チャンネル名）
const PRESENTER = "ずんだもん";

// カテゴリ定義（key はデータと一致させる。color はサムネイルの配色に使われます）
const CATEGORIES = [
  { key: "all",        label: "ホーム",       icon: "🏠", color: "#ef4444" },
  { key: "基礎看護学",   label: "基礎看護学",   icon: "🩺", color: "#2563eb" },
  { key: "解剖生理学",   label: "解剖生理学",   icon: "🫀", color: "#db2777" },
  { key: "薬理学",      label: "薬理学",       icon: "💊", color: "#7c3aed" },
  { key: "疾患・病態",   label: "疾患・病態",   icon: "🧬", color: "#16a34a" },
  { key: "看護技術",     label: "看護技術",     icon: "💉", color: "#0891b2" },
  { key: "母性・小児",   label: "母性・小児",   icon: "🍼", color: "#f59e0b" },
  { key: "精神看護",     label: "精神看護",     icon: "🧠", color: "#4f46e5" },
  { key: "国家試験対策", label: "国家試験対策", icon: "📝", color: "#dc2626" },
];

// 番組（学習動画）カタログ ── 解説はぜんぶ「ずんだもん」がしてくれるのだ
const PROGRAMS = [
  // --- 解剖生理学 ---
  {
    id: "anat01",
    title: "心臓の解剖と血液の流れを10分で完全マスター",
    category: "解剖生理学",
    channel: PRESENTER,
    durationSec: 612,
    views: 128400,
    published: "2026-04-12",
    videoId: "",
    description: "心臓は右心房・右心室・左心房・左心室の4つの部屋でできているのだ。体循環と肺循環で血液がどう流れるかを、図解でいっしょに整理するのだ。弁の名前と役割、心電図とのつながりまで、国試で問われるところをまとめて覚えるのだ!",
    tags: ["循環器", "解剖", "必修"],
  },
  {
    id: "anat02",
    title: "腎臓のはたらき｜ネフロンと尿ができる仕組み",
    category: "解剖生理学",
    channel: PRESENTER,
    durationSec: 845,
    views: 96200,
    published: "2026-03-02",
    videoId: "",
    description: "おしっこができるしくみを解説するのだ。糸球体でこしとって、尿細管で必要なものを再吸収する流れをステップで見ていくのだ。RAA系やADHによる調節、電解質バランスとのつながりも押さえるのだ。",
    tags: ["腎・泌尿器", "解剖", "国試"],
  },
  {
    id: "anat03",
    title: "呼吸のメカニズムとガス交換のしくみ",
    category: "解剖生理学",
    channel: PRESENTER,
    durationSec: 540,
    views: 71300,
    published: "2026-02-18",
    videoId: "",
    description: "息を吸って吐く『外呼吸』と、細胞でおこなう『内呼吸』のちがいを解説するのだ。酸素解離曲線や、換気と血流の関係まで、SpO2やPaO2の読み方につながる知識をまとめるのだ。",
    tags: ["呼吸器", "解剖"],
  },
  {
    id: "anat04",
    title: "自律神経まとめ｜交感神経と副交感神経の作用一覧",
    category: "解剖生理学",
    channel: PRESENTER,
    durationSec: 498,
    views: 113900,
    published: "2026-05-09",
    videoId: "",
    description: "交感神経と副交感神経、どっちがどんな働きをするのかを表でまとめて覚えるのだ。瞳孔・心拍・消化・血圧の変化を整理すれば、自律神経にはたらくお薬の理解もぐっとラクになるのだ!",
    tags: ["神経", "暗記", "薬理連携"],
  },
  {
    id: "anat05",
    title: "ホルモンと内分泌系の全体像をスッキリ整理",
    category: "解剖生理学",
    channel: PRESENTER,
    durationSec: 760,
    views: 58700,
    published: "2026-01-21",
    videoId: "",
    description: "視床下部→下垂体→標的器官という、ホルモンの命令がつたわる流れを解説するのだ。主要なホルモンの働きと、出すぎ・足りないときに起こる病気をセットで覚えるのだ。",
    tags: ["内分泌", "解剖"],
  },

  // --- 基礎看護学 ---
  {
    id: "base01",
    title: "バイタルサイン測定の基本と正常値【保存版】",
    category: "基礎看護学",
    channel: PRESENTER,
    durationSec: 935,
    views: 204500,
    published: "2026-04-28",
    videoId: "",
    description: "体温・脈拍・呼吸・血圧・SpO2の正常値と測り方を、実演をまじえて解説するのだ。異常があったときの考え方も身につくのだ。実習の前にぜったい見てほしい1本なのだ!",
    tags: ["バイタル", "必修", "実習前"],
  },
  {
    id: "base02",
    title: "感染予防の基本｜スタンダードプリコーションと手指衛生5つの瞬間",
    category: "基礎看護学",
    channel: PRESENTER,
    durationSec: 612,
    views: 88100,
    published: "2026-03-15",
    videoId: "",
    description: "標準予防策(スタンダードプリコーション)の考え方を解説するのだ。手指衛生をするタイミング『5つの瞬間』や、防護具(PPE)の正しい着脱の順番までいっしょに確認するのだ。",
    tags: ["感染", "実習前", "必修"],
  },
  {
    id: "base03",
    title: "看護過程の進め方｜アセスメントから看護診断まで",
    category: "基礎看護学",
    channel: PRESENTER,
    durationSec: 1080,
    views: 67400,
    published: "2026-02-06",
    videoId: "",
    description: "情報収集→アセスメント→看護診断→計画→実施→評価という看護過程の流れを、具体例でやさしく解説するのだ。実習記録が苦手でもだいじょうぶ、いっしょにやれば書けるようになるのだ!",
    tags: ["看護過程", "実習", "記録"],
  },
  {
    id: "base04",
    title: "SOAPの書き方入門｜記録が苦手でも書けるコツ",
    category: "基礎看護学",
    channel: PRESENTER,
    durationSec: 524,
    views: 79900,
    published: "2026-05-20",
    videoId: "",
    description: "記録のS(主観)・O(客観)・A(アセスメント)・P(計画)の分け方を、例文で解説するのだ。よくあるまちがいも紹介するから、これを見れば実習記録がスラスラ書けるようになるのだ。",
    tags: ["記録", "実習"],
  },

  // --- 看護技術 ---
  {
    id: "skill01",
    title: "静脈血採血の手順とコツ｜駆血から抜針まで",
    category: "看護技術",
    channel: PRESENTER,
    durationSec: 702,
    views: 152300,
    published: "2026-04-03",
    videoId: "",
    description: "静脈血採血のやり方を、駆血から抜針・止血までじっくり解説するのだ。血管の選び方や刺す角度、スピッツの順番、そして神経を傷つけないためのコツまで教えるのだ!",
    tags: ["採血", "手技", "実習"],
  },
  {
    id: "skill02",
    title: "膀胱留置カテーテルの挿入｜無菌操作のポイント",
    category: "看護技術",
    channel: PRESENTER,
    durationSec: 688,
    views: 64800,
    published: "2026-03-22",
    videoId: "",
    description: "膀胱留置カテーテルの入れ方を、無菌操作のポイントといっしょに解説するのだ。男性と女性の解剖のちがい、消毒の範囲、固定水の量、感染予防の注意点までしっかり押さえるのだ。",
    tags: ["導尿", "手技", "感染予防"],
  },
  {
    id: "skill03",
    title: "褥瘡予防とポジショニング｜体位変換の基本",
    category: "看護技術",
    channel: PRESENTER,
    durationSec: 595,
    views: 51200,
    published: "2026-02-11",
    videoId: "",
    description: "褥瘡(床ずれ)を防ぐポジショニングと体位変換の基本を解説するのだ。DESIGN-R®の見方や好発部位、30度側臥位、ずれと圧を減らすコツをまとめるのだ。",
    tags: ["褥瘡", "スキンケア"],
  },
  {
    id: "skill04",
    title: "経鼻胃管(NGチューブ)挿入と管理のポイント",
    category: "看護技術",
    channel: PRESENTER,
    durationSec: 640,
    views: 43900,
    published: "2026-01-30",
    videoId: "",
    description: "経鼻胃管(NGチューブ)の入れ方と管理を解説するのだ。長さの測り方や位置の確認方法、固定、栄養剤を入れるときの注意点まで、誤挿入を防ぐ手順を重点的にやるのだ。",
    tags: ["経管栄養", "手技"],
  },
  {
    id: "skill05",
    title: "口腔・鼻腔・気管吸引の手順と注意点",
    category: "看護技術",
    channel: PRESENTER,
    durationSec: 558,
    views: 60100,
    published: "2026-05-02",
    videoId: "",
    description: "口腔・鼻腔・気管の吸引の手順を解説するのだ。吸引圧や1回の吸引時間、低酸素を防ぐコツ、清潔操作のポイントを、SpO2を見まもりながら確認するのだ。",
    tags: ["吸引", "呼吸", "手技"],
  },

  // --- 薬理学 ---
  {
    id: "pharm01",
    title: "降圧薬の種類と作用機序をまとめて理解",
    category: "薬理学",
    channel: PRESENTER,
    durationSec: 815,
    views: 92700,
    published: "2026-04-18",
    videoId: "",
    description: "血圧を下げるお薬を、種類ごとの効き方でまとめて解説するのだ。Ca拮抗薬・ARB・ACE阻害薬・利尿薬・β遮断薬の作用点と代表的な副作用を、図と語呂で覚えるのだ!",
    tags: ["循環器", "薬理", "国試"],
  },
  {
    id: "pharm02",
    title: "インスリン製剤の種類と作用時間【超速効〜持効型】",
    category: "薬理学",
    channel: PRESENTER,
    durationSec: 612,
    views: 70500,
    published: "2026-03-08",
    videoId: "",
    description: "インスリン製剤を超速効型から持効型まで、効きはじめと続く時間で整理するのだ。低血糖の症状や、シックデイのときの対応もいっしょに覚えておくのだ。",
    tags: ["糖尿病", "薬理", "必修"],
  },
  {
    id: "pharm03",
    title: "抗菌薬の分類と使い分けの基本",
    category: "薬理学",
    channel: PRESENTER,
    durationSec: 705,
    views: 38600,
    published: "2026-02-24",
    videoId: "",
    description: "抗菌薬の分類と使い分けの基本を解説するのだ。βラクタム系・マクロライド系・キノロン系の効き方や、MRSAみたいな耐性菌のことも分かりやすくまとめるのだ。",
    tags: ["感染", "薬理"],
  },
  {
    id: "pharm04",
    title: "利尿薬まとめ｜ループ・サイアザイド・K保持性",
    category: "薬理学",
    channel: PRESENTER,
    durationSec: 486,
    views: 33100,
    published: "2026-01-14",
    videoId: "",
    description: "利尿薬を、はたらく場所ごとに整理するのだ。ループ・サイアザイド・K保持性のちがいと、カリウムへの影響(低K・高K)、観察のポイントを表でまとめるのだ。",
    tags: ["腎・泌尿器", "薬理"],
  },

  // --- 疾患・病態 ---
  {
    id: "dis01",
    title: "心不全の病態と看護｜左心不全と右心不全の違い",
    category: "疾患・病態",
    channel: PRESENTER,
    durationSec: 920,
    views: 84300,
    published: "2026-05-12",
    videoId: "",
    description: "心不全を、左心不全と右心不全に分けて解説するのだ。前負荷・後負荷の考え方から、肺うっ血と体うっ血の症状のちがい、観察と看護のポイントまでつかむのだ。",
    tags: ["循環器", "病態", "国試"],
  },
  {
    id: "dis02",
    title: "糖尿病の3大合併症をイメージで覚える",
    category: "疾患・病態",
    channel: PRESENTER,
    durationSec: 588,
    views: 119800,
    published: "2026-04-06",
    videoId: "",
    description: "糖尿病の3大合併症『神経・目・腎臓』をイメージで覚えるのだ。それぞれが起こるしくみと進み方、フットケアや血糖コントロールの指導内容まで解説するのだ。",
    tags: ["糖尿病", "病態", "必修"],
  },
  {
    id: "dis03",
    title: "脳梗塞の分類と症状｜FASTで早期発見",
    category: "疾患・病態",
    channel: PRESENTER,
    durationSec: 640,
    views: 56700,
    published: "2026-03-19",
    videoId: "",
    description: "脳梗塞を、アテローム血栓性・心原性・ラクナの3タイプに分けて解説するのだ。t-PAが使える時間や、片麻痺・失語などの症状と看護を、合言葉『FAST』で早期発見につなげるのだ!",
    tags: ["脳神経", "病態"],
  },
  {
    id: "dis04",
    title: "COPDの病態と看護｜口すぼめ呼吸の意味",
    category: "疾患・病態",
    channel: PRESENTER,
    durationSec: 552,
    views: 41500,
    published: "2026-02-02",
    videoId: "",
    description: "COPDで息が吐きにくくなるしくみを解説するのだ。CO2ナルコーシスの注意点や、口すぼめ呼吸にどんな意味があるのか、呼吸リハと栄養管理のポイントまでまとめるのだ。",
    tags: ["呼吸器", "病態"],
  },

  // --- 母性・小児 ---
  {
    id: "mat01",
    title: "正常分娩の経過と看護｜分娩第1期〜第4期",
    category: "母性・小児",
    channel: PRESENTER,
    durationSec: 880,
    views: 47200,
    published: "2026-04-22",
    videoId: "",
    description: "赤ちゃんが生まれるまでの正常分娩を、第1期から第4期まで順番に解説するのだ。分娩の3要素や、各期の所要時間と観察項目、産婦さんへの声かけのポイントをつかむのだ。",
    tags: ["母性", "分娩"],
  },
  {
    id: "ped01",
    title: "新生児の生理とアセスメント｜アプガースコア",
    category: "母性・小児",
    channel: PRESENTER,
    durationSec: 624,
    views: 39800,
    published: "2026-03-11",
    videoId: "",
    description: "生まれたての赤ちゃんのアセスメントを解説するのだ。アプガースコアの5項目や、生理的体重減少・黄疸・原始反射など、新生児ならではの特徴をやさしくまとめるのだ。",
    tags: ["小児", "新生児"],
  },

  // --- 精神看護 ---
  {
    id: "psy01",
    title: "統合失調症の症状と看護｜陽性症状と陰性症状",
    category: "精神看護",
    channel: PRESENTER,
    durationSec: 705,
    views: 52600,
    published: "2026-05-16",
    videoId: "",
    description: "統合失調症の症状を、陽性症状(幻覚・妄想)と陰性症状(感情鈍麻・意欲低下)に分けて解説するのだ。お薬を続ける支援や、再発を防ぐ関わり方もいっしょに学ぶのだ。",
    tags: ["精神", "看護"],
  },
  {
    id: "psy02",
    title: "うつ病の理解と関わり方｜してはいけない声かけ",
    category: "精神看護",
    channel: PRESENTER,
    durationSec: 567,
    views: 61900,
    published: "2026-04-09",
    videoId: "",
    description: "うつ病の症状と経過を解説するのだ。つらい気持ちへの寄りそい方や、『がんばって』という励ましがどうして逆効果になってしまうのかを、具体例でやさしく説明するのだ。",
    tags: ["精神", "看護"],
  },

  // --- 国家試験対策 ---
  {
    id: "exam01",
    title: "必修問題でよく出る正常値まとめ【一問一答】",
    category: "国家試験対策",
    channel: PRESENTER,
    durationSec: 738,
    views: 233100,
    published: "2026-05-25",
    videoId: "",
    description: "必修問題でねらわれる正常値を、一問一答で確認するのだ。バイタル・血液・電解質・尿の基準値を厳選したから、必修8割の壁をいっしょに超えるのだ!",
    tags: ["必修", "暗記", "国試"],
  },
  {
    id: "exam02",
    title: "点滴の滴下数 計算問題の解き方【公式と練習】",
    category: "国家試験対策",
    channel: PRESENTER,
    durationSec: 612,
    views: 187500,
    published: "2026-04-15",
    videoId: "",
    description: "点滴の滴下数の計算を、公式の使い方から解説するのだ。成人用(20滴=1mL)と小児用(60滴=1mL)の使い分けと、よく出る計算パターンを練習問題で攻略するのだ。",
    tags: ["計算", "必修", "国試"],
  },
  {
    id: "exam03",
    title: "心電図の読み方の基本｜まずはこの3つから",
    category: "国家試験対策",
    channel: PRESENTER,
    durationSec: 690,
    views: 98400,
    published: "2026-03-28",
    videoId: "",
    description: "心電図の読み方を、まずはこの3つから解説するのだ。正常な波形の見方と、心房細動・心室細動・心室頻拍みたいな危険な波形の特徴を、最低限のところからつかむのだ。",
    tags: ["循環器", "心電図", "国試"],
  },
];
